### PR TITLE
Adding js-training.yml (workshop modules for nationalparks-js)

### PR DESCRIPTION
**Pull request by ryanj**
Preview available here: http://workshop-worktown.b9ad.pro-us-east-1.openshiftapps.com/

### CODE REVIEW

**Comment by ryanj** [comment]
Preview available here: http://workshop-worktown.b9ad.pro-us-east-1.openshiftapps.com/

**Comment by jorgemoralespou** [comment]
@ryanj there's changes missing in the web hook chapter

**Comment by ryanj** [comment]
Thanks @jorgemoralespou - Changes pushed

I think it's ready for another look

**Comment by ryanj** [comment]
Most of my changes are new files, but I did not duplicate the `codechanges.adoc` file. 

It might be a good idea to re-test the other training content (which also depends on `codechanges.adoc`) - to make sure I didn't break anyone else's content.

**Comment by ryanj** [comment]
cc @marekjelen

**Comment by jorgemoralespou** [comment]
This should already be fixed. There's a https://github.com/openshift-labs/starter-guides/blob/ocp-3.9/_workshops/javascript-starter-guides.yml definition

**Pull request closed without merging**
